name: development
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: actions/setup-go@v1
      with:
        go-version: '1.15.7'

    - name: build
      env:
        GOPATH: "/tmp"
      run: |
          go build ./cmd/wasped

    - name: test
      env:
        GOPATH: "/tmp"
      run: |
          go test -cover ./...

